/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * An Ed25519 key pair for signing and verification.
 *
 * The private key is held securely in Rust memory and never exposed to JavaScript.
 * Use `sign()` to create signatures and `verify()` for verification.
 */
export declare class KeyPair {
  /** Generate a new random Ed25519 key pair. */
  static generate(): KeyPair
  /**
   * Create a key pair from secret key bytes (32 bytes).
   *
   * WARNING: Only use for loading previously saved keys.
   * Prefer generate() for new keys.
   */
  static fromSecretBytes(secret: Buffer): KeyPair
  /** Sign a message and return the signature as bytes. */
  sign(message: Buffer): Buffer
  /** Verify a signature against a message using this key pair's public key. */
  verify(message: Buffer, signature: Buffer): boolean
  /** Get the public key in multibase encoding (z-prefixed base58btc). */
  get publicKeyMultibase(): string
  /** Get the raw public key bytes (32 bytes). */
  get publicKeyBytes(): Buffer
}
export type AID = Aid
/**
 * An IDProva Agent Identity Document (W3C DID Document).
 *
 * Create with AIDBuilder or parse from JSON.
 */
export declare class Aid {
  /** Get the DID identifier (e.g., "did:idprova:example.com:my-agent"). */
  get did(): string
  /** Get the controller DID. */
  get controller(): string
  /** Get the trust level string (e.g., "L0", "L1"). */
  get trustLevel(): string | null
  /** Serialize to JSON string. */
  toJson(): string
  /** Parse from JSON string. */
  static fromJson(json: string): Aid
  /** Validate the document structure. */
  validate(): void
}
export type AIDBuilder = AidBuilder
/**
 * Builder for creating Agent Identity Documents.
 *
 * Usage:
 *   const builder = new AIDBuilder();
 *   builder.setId("did:idprova:example.com:my-agent");
 *   builder.setController("did:idprova:example.com:alice");
 *   builder.setName("My Agent");
 *   builder.addEd25519Key(keypair);
 *   const aid = builder.build();
 */
export declare class AidBuilder {
  constructor()
  /** Set the DID identifier. */
  setId(id: string): void
  /** Set the controller DID. */
  setController(controller: string): void
  /** Set the human-readable agent name. */
  setName(name: string): void
  /** Set an optional description. */
  setDescription(desc: string): void
  /** Set the AI model identifier. */
  setModel(model: string): void
  /** Set the runtime environment. */
  setRuntime(runtime: string): void
  /** Set the trust level (e.g., "L0", "L1"). */
  setTrustLevel(level: string): void
  /** Add an Ed25519 verification key from a KeyPair. */
  addEd25519Key(keypair: KeyPair): void
  /** Build and validate the AID document. */
  build(): Aid
}
export type DAT = Dat
/**
 * A Delegation Attestation Token — signed, scoped, time-bounded permission grant.
 *
 * Issue with DAT.issue(), parse with DAT.fromCompact().
 */
export declare class Dat {
  /** Issue a new DAT signed by the issuer's key pair. */
  static issue(issuerDid: string, subjectDid: string, scope: Array<string>, expiresInSeconds: number, signingKey: KeyPair, maxActions?: number | undefined | null, requireReceipt?: boolean | undefined | null): Dat
  /** Serialize to compact JWS format (header.payload.signature). */
  toCompact(): string
  /** Parse from compact JWS string (validates algorithm). */
  static fromCompact(compact: string): Dat
  /** Verify the DAT signature against a public key (Buffer, 32 bytes). */
  verifySignature(publicKeyBytes: Buffer): boolean
  /** Validate timing constraints (not expired, not before valid). */
  validateTiming(): void
  /** Check if the DAT is expired. */
  get isExpired(): boolean
  /** Get the issuer DID. */
  get issuer(): string
  /** Get the subject DID. */
  get subject(): string
  /** Get the token ID (jti). */
  get jti(): string
  /** Get the granted scopes as a list of strings. */
  get scope(): Array<string>
  /** Get the expiration timestamp (Unix seconds). */
  get expiresAt(): number
}
/** A permission scope in namespace:resource:action format. */
export declare class Scope {
  /** Parse a scope string (e.g., "mcp:tool:read"). */
  constructor(scopeStr: string)
  /** Check if this scope covers (permits) the requested scope. */
  covers(requested: Scope): boolean
  /** Get the string representation. */
  toStringRepr(): string
}
/** Trust level for an agent identity (L0 through L4). */
export declare class TrustLevel {
  /** Parse a trust level string (e.g., "L0", "L1", "L2", "L3", "L4"). */
  constructor(level: string)
  /** Check if this trust level meets the required minimum. */
  meetsMinimum(required: TrustLevel): boolean
  /** Get a human-readable description of this trust level. */
  get description(): string
  /** Get the string representation (e.g., "L0"). */
  toStringRepr(): string
}
/**
 * An append-only, hash-chained audit receipt log.
 *
 * Provides tamper-evident logging of agent actions.
 */
export declare class ReceiptLog {
  /** Create a new empty receipt log. */
  constructor()
  /**
   * Verify the integrity of the entire receipt chain.
   * Throws an error if any receipt has been tampered with.
   */
  verifyIntegrity(): void
  /** Get the hash of the last receipt (or "genesis" if empty). */
  get lastHash(): string
  /** Get the next sequence number. */
  get nextSequence(): number
  /** Get the number of entries in the log. */
  get length(): number
  /** Serialize the log to JSON string. */
  toJson(): string
}
/**
 * High-level convenience class for creating agent identities.
 *
 * Usage:
 *   const identity = AgentIdentity.create("my-agent", "example.com");
 *   console.log(identity.did);
 */
export declare class AgentIdentity {
  /**
   * Create a new agent identity with a generated key pair.
   *
   * @param name - Agent name (lowercase alphanumeric + hyphens)
   * @param domain - Domain namespace (default: "local.dev")
   * @param controller - Controller DID (default: auto-generated)
   */
  static create(name: string, domain?: string | undefined | null, controller?: string | undefined | null): AgentIdentity
  /** Get the DID identifier. */
  get did(): string
  /** Get the AID document. */
  aid(): Aid
  /** Get the key pair (for signing operations). */
  keypair(): KeyPair
  /** Issue a delegation token to another agent. */
  issueDat(subjectDid: string, scope: Array<string>, expiresInSeconds?: number | undefined | null): Dat
  /** Get the public key bytes (32 bytes). */
  get publicKeyBytes(): Buffer
}
