// IDProva Core TypeScript SDK
//
// This file is the TypeScript source reference.
// The actual published package uses napi-rs generated index.js + index.d.ts.
//
// Usage:
//   import { KeyPair, AID, DAT, ReceiptLog, AgentIdentity } from '@idprova/core';
//
//   const identity = AgentIdentity.create("my-agent", "example.com");
//   console.log(identity.did);
//
//   const dat = identity.issueDat(
//     "did:idprova:example.com:sub-agent",
//     ["mcp:tool:read"],
//     3600,
//   );
//   console.log(dat.toCompact());

export const VERSION = '0.1.0';

// Exports are generated by napi-rs from src/native.rs
// See: @napi-rs/cli build output for index.js + index.d.ts
